#!/usr/bin/env Rscript

cat("==============================================================================\n")
cat("Mass-weighted first stage: diagnostics\n")
cat("==============================================================================\n\n")

source("R/00_helpers.R")

panel <- read_qs_dt(out_path("horserace_panel_long.qs2"))
panel[, spec := as.character(spec)]
panel[, shift := as.character(shift)]
panel[, channel := as.character(channel)]
panel[, policy_block := as.character(policy_block)]

cat("Rank correlations across policy blocks...\n")
rank_wide <- dcast(
  panel,
  muni_id + year + channel + shift + policy_block ~ spec,
  value.var = "Z",
  fill = 0
)
spec_pairs <- list(c("BASE", "VAR-A"), c("BASE", "VAR-B"), c("VAR-A", "VAR-B"))

rank_rows <- list()
for (pair in spec_pairs) {
  a <- pair[1]
  b <- pair[2]
  tmp <- rank_wide[, {
    ok <- is.finite(get(a)) & is.finite(get(b))
    rho <- if (sum(ok) >= 2L &&
               uniqueN(get(a)[ok]) > 1L &&
               uniqueN(get(b)[ok]) > 1L) {
      suppressWarnings(cor(get(a)[ok], get(b)[ok], method = "spearman"))
    } else {
      NA_real_
    }
    .(spearman_rho = rho)
  }, by = .(muni_id, year, channel, shift)]
  tmp[, pair := paste(a, b, sep = "_vs_")]
  rank_rows[[length(rank_rows) + 1L]] <- tmp
}
rank_dt <- rbindlist(rank_rows)
write_csv_atomic(rank_dt, out_path("rank_correlations.csv"))

rank_summary <- rank_dt[, .(
  n = sum(!is.na(spearman_rho)),
  mean = mean(spearman_rho, na.rm = TRUE),
  p05 = quantile(spearman_rho, 0.05, na.rm = TRUE, names = FALSE),
  p25 = quantile(spearman_rho, 0.25, na.rm = TRUE, names = FALSE),
  median = median(spearman_rho, na.rm = TRUE),
  p75 = quantile(spearman_rho, 0.75, na.rm = TRUE, names = FALSE),
  p95 = quantile(spearman_rho, 0.95, na.rm = TRUE, names = FALSE)
), by = .(pair, channel, shift)]
setorder(rank_summary, pair, shift, channel)
write_csv_atomic(rank_summary, out_path("rank_correlation_summary.csv"))

tex <- c(
  "% Auto-generated by R/03_diagnostics.R",
  "\\begin{table}[!htbp]",
  "\\centering",
  "\\caption{Within-municipality Spearman rank correlations across policy blocks}",
  "\\begin{tabular}{llllrrrr}",
  "\\toprule",
  "Pair & Channel & Shift & N & Mean & P25 & Median & P75 \\\\",
  "\\midrule"
)
for (i in seq_len(nrow(rank_summary))) {
  tex <- c(tex, sprintf(
    "%s & %s & %s & %d & %s & %s & %s & %s \\\\",
    gsub("_vs_", " vs ", rank_summary$pair[i]),
    rank_summary$channel[i],
    rank_summary$shift[i],
    rank_summary$n[i],
    fmt_num(rank_summary$mean[i], 3),
    fmt_num(rank_summary$p25[i], 3),
    fmt_num(rank_summary$median[i], 3),
    fmt_num(rank_summary$p75[i], 3)
  ))
}
tex <- c(tex, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(tex, out_path("rank_correlation_summary.tex"))

cat("Herfindahl distributions...\n")
hhi <- panel[, .(
  herfindahl_Z = sum(Z^2, na.rm = TRUE)
), by = .(spec, muni_id, year, channel, shift)]
hhi[, event_type := event_type_for_year(year)]
write_csv_atomic(hhi, out_path("herfindahl_distribution.csv"))

hhi_summary <- hhi[, .(
  n = .N,
  mean = mean(herfindahl_Z, na.rm = TRUE),
  p50 = median(herfindahl_Z, na.rm = TRUE),
  p75 = quantile(herfindahl_Z, 0.75, na.rm = TRUE, names = FALSE),
  p95 = quantile(herfindahl_Z, 0.95, na.rm = TRUE, names = FALSE),
  p99 = quantile(herfindahl_Z, 0.99, na.rm = TRUE, names = FALSE)
), by = .(spec, channel, shift)]
setorder(hhi_summary, spec, shift, channel)
write_csv_atomic(hhi_summary, out_path("herfindahl_distribution_summary.csv"))

pdf(out_path("herfindahl_distribution.pdf"), width = 11, height = 7)
if (requireNamespace("ggplot2", quietly = TRUE)) {
  print(
    ggplot2::ggplot(hhi, ggplot2::aes(x = spec, y = herfindahl_Z, fill = spec)) +
      ggplot2::geom_boxplot(outlier.alpha = 0.15) +
      ggplot2::facet_grid(shift ~ channel, scales = "free_y") +
      ggplot2::theme_minimal(base_size = 10) +
      ggplot2::theme(legend.position = "none") +
      ggplot2::labs(x = NULL, y = "sum_j Z_jmt^2")
  )
} else {
  par(mfrow = c(2, 4), mar = c(4, 4, 2, 1))
  for (sh in c("LEV", "DIF")) {
    for (ch in channel_map$channel) {
      boxplot(
        herfindahl_Z ~ spec,
        data = hhi[shift == sh & channel == ch],
        main = paste(sh, ch),
        ylab = "sum_j Z^2",
        xlab = ""
      )
    }
  }
}
dev.off()

cat("VAR-B vs VAR-A disagreement municipalities...\n")
disagree <- rank_dt[pair == "VAR-A_vs_VAR-B", .(
  mean_rho = mean(spearman_rho, na.rm = TRUE),
  min_rho = min(spearman_rho, na.rm = TRUE),
  n_valid = sum(!is.na(spearman_rho)),
  disagreement_score = mean(1 - spearman_rho, na.rm = TRUE)
), by = muni_id]
disagree <- disagree[is.finite(disagreement_score)]
setorder(disagree, -disagreement_score, mean_rho, muni_id)
top50 <- head(disagree, 50L)
write_csv_atomic(top50, out_path("disagreement_munis.csv"))

cat("DIF event-year decomposition...\n")
dif <- panel[shift == "DIF"]
dif[, event_type := event_type_for_year(year)]
decomp <- dif[, .(
  n_rows = .N,
  n_munis = uniqueN(muni_id),
  sum_abs_Z = sum(abs(Z), na.rm = TRUE),
  sum_sq_Z = sum(Z^2, na.rm = TRUE),
  mean_abs_Z = mean(abs(Z), na.rm = TRUE)
), by = .(spec, channel, event_type)]
decomp[, total_sq_channel := sum(sum_sq_Z, na.rm = TRUE), by = .(spec, channel)]
decomp[, share_sq_Z := fifelse(total_sq_channel > 0, sum_sq_Z / total_sq_channel, NA_real_)]
setorder(decomp, spec, channel, event_type)
write_csv_atomic(decomp, out_path("dif_event_year_decomposition.csv"))

cat("\nSaved diagnostics:\n")
cat("  ", out_path("rank_correlation_summary.tex"), "\n", sep = "")
cat("  ", out_path("herfindahl_distribution.pdf"), "\n", sep = "")
cat("  ", out_path("disagreement_munis.csv"), "\n", sep = "")
cat("  ", out_path("dif_event_year_decomposition.csv"), "\n", sep = "")
cat("\nDiagnostics complete.\n")
